---
input_tasks_run_order:
  - name: fetch-kubeconfig.yml
  - name: install-packages.yml
    vars:
      - ubuntu-packages.vars.yml
  - name: install-other-packages-apt.yml
    vars:
      - ubuntu-packages.vars.yml
  - name: install-helm-charts.yml
    vars:
      - helm-charts.vars.yml
...
