---
- hosts: all
  gather_facts: true
  vars:
    playbook_tasks_run_order:
      - name: EXAMPLE_test.yml
        vars:
          - EXAMPLE_test.vars.yml
      - name: EXAMPLE_echo.yml
        vars:
          - EXAMPLE_echo.vars.yml
  tasks:
    - name: "Execute subtasks"
      ansible.builtin.include_tasks: utils/execute_task.yml
      vars:
        load_task: "subtask/{{ task.name }}"
        load_vars: "{{ task.vars | map('regex_replace', '^(.*)$', 'subtask_vars/\\1') | list }}"
      loop_control:
        loop_var: task
      loop: "{{ playbook_tasks_run_order }}"
...
