---
- name: Modify kubeconfig and store to localhost
  when: inventory_hostname in groups['kube_control_plane']
  run_once: true # This can cause a bug! If k8s-1 is not control plane, it will fail.
  block:
    - name: Copy kubeconfig on VM
      ansible.builtin.copy:
        src: /root/.kube/config
        dest: /home/vagrant/config
        remote_src: true

    - name: Modify 127.0.0.1 to VM accessible IP
      ansible.builtin.replace:
        path: /home/vagrant/config
        regexp: '127\.0\.0\.1'
        replace: '{{ ansible_eth1.ipv4.address }}'

    - name: Fetch kubeconfig to localhost
      ansible.builtin.fetch:
        src: /home/vagrant/config
        dest: "{{ playbook_dir }}/.kubeconfig"
        flat: true
...
